# CHROMIUM UI LIB contains org.chromium.ui.* sources

# Make sure you setup and run ../../env.sh first

export PROJ=$ACV_HOME/ui

# cleanup
rm -rf $PROJ/src/org/chromium/ui/*
rm -rf $PROJ/res/*

# copy android ui sources org.chromium.ui
scp -r $BUILD/ui/android/java/src/* $PROJ/src/

# copy android ui resources
scp -r $BUILD/ui/android/java/res/* $PROJ/res/

# strings are generated by chromium build, not by standard android strings.xml
scp -r $BUILD/out/Release/gen/ui_java/res_grit/values/* $PROJ/res/values/


